##### 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [1]:
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(3, 3))
print("Original Array:")
print(arr)

# Interchange rows and columns (transpose the array)
transposed_arr = np.transpose(arr)
print("\nTransposed Array:")
print(transposed_arr)


Original Array:
[[ 61 100  52]
 [ 23  55  71]
 [ 47  45  51]]

Transposed Array:
[[ 61  23  47]
 [100  55  45]
 [ 52  71  51]]


##### 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [2]:
import numpy as np

# Generate a 1D array with 10 elements
arr = np.arange(10)
print("Original 1D Array:")
print(arr)

# Reshape it into a 2x5 array
reshaped_2x5 = arr.reshape(2, 5)
print("\nReshaped into 2x5 Array:")
print(reshaped_2x5)

# Reshape it into a 5x2 array
reshaped_5x2 = arr.reshape(5, 2)
print("\nReshaped into 5x2 Array:")
print(reshaped_5x2)


Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped into 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped into 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


##### 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [3]:
import numpy as np

# Create a 4x4 array with random float values
arr = np.random.rand(4, 4)
print("Original 4x4 Array:")
print(arr)

# Add a border of zeros around the array (resulting in a 6x6 array)
arr_with_border = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print("\nArray with Border (6x6 Array):")
print(arr_with_border)


Original 4x4 Array:
[[6.83962311e-01 2.57498396e-04 2.62823638e-01 7.97067677e-02]
 [9.32906690e-01 5.59318045e-01 2.97725949e-01 2.09737876e-01]
 [4.86703950e-01 3.74771234e-01 6.87884984e-01 1.40378174e-01]
 [4.91459010e-01 2.53696634e-01 4.10461583e-01 6.77666026e-01]]

Array with Border (6x6 Array):
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 6.83962311e-01 2.57498396e-04 2.62823638e-01
  7.97067677e-02 0.00000000e+00]
 [0.00000000e+00 9.32906690e-01 5.59318045e-01 2.97725949e-01
  2.09737876e-01 0.00000000e+00]
 [0.00000000e+00 4.86703950e-01 3.74771234e-01 6.87884984e-01
  1.40378174e-01 0.00000000e+00]
 [0.00000000e+00 4.91459010e-01 2.53696634e-01 4.10461583e-01
  6.77666026e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]]


##### 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [4]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
arr = np.arange(10, 61, 5)
print("Array with integers from 10 to 60 with a step of 5:")
print(arr)


Array with integers from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


##### 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [5]:
import numpy as np

# Creating a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Applying different case transformations
uppercase_array = np.char.upper(array)
lowercase_array = np.char.lower(array)
titlecase_array = np.char.title(array)
swapcase_array = np.char.swapcase(array)

print("Original array:")
print(array)

print("\nUppercase array:")
print(uppercase_array)

print("\nLowercase array:")
print(lowercase_array)

print("\nTitlecase array:")
print(titlecase_array)

print("\nSwapcase array:")
print(swapcase_array)


Original array:
['python' 'numpy' 'pandas']

Uppercase array:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase array:
['python' 'numpy' 'pandas']

Titlecase array:
['Python' 'Numpy' 'Pandas']

Swapcase array:
['PYTHON' 'NUMPY' 'PANDAS']


##### 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [6]:
import numpy as np

# Creating a NumPy array of words
words = np.array(['python', 'numpy', 'pandas'])

# Function to insert spaces between characters
def insert_spaces(word):
    return ' '.join(list(word))

# Applying the function to each element in the array
spaced_words = np.vectorize(insert_spaces)(words)

print("Original array:")
print(words)

print("\nArray with spaces between characters:")
print(spaced_words)


Original array:
['python' 'numpy' 'pandas']

Array with spaces between characters:
['p y t h o n' 'n u m p y' 'p a n d a s']


##### 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [7]:
import numpy as np

# Creating two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Element-wise addition
addition = np.add(array1, array2)

# Element-wise subtraction
subtraction = np.subtract(array1, array2)

# Element-wise multiplication
multiplication = np.multiply(array1, array2)

# Element-wise division
division = np.divide(array1, array2)

print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nElement-wise Addition:")
print(addition)

print("\nElement-wise Subtraction:")
print(subtraction)

print("\nElement-wise Multiplication:")
print(multiplication)

print("\nElement-wise Division:")
print(division)


Array 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array 2:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Element-wise Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Element-wise Subtraction:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Element-wise Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Element-wise Division:
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


##### 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [8]:
import numpy as np

# Creating a 5x5 identity matrix
identity_matrix = np.identity(5)

print("Identity Matrix:")
print(identity_matrix)

# Extracting the diagonal elements
diagonal_elements = np.diag(identity_matrix)

print("\nDiagonal Elements:")
print(diagonal_elements)


Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


##### 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [9]:
import numpy as np

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

# Generate an array of 100 random integers between 0 and 1000
arr = np.random.randint(0, 1001, size=100)
print("Array of random integers:")
print(arr)

# Find all prime numbers in the array
primes = np.array([num for num in arr if is_prime(num)])

print("\nPrime numbers in the array:")
print(primes)


Array of random integers:
[737 247 463 600 573 636 446 957 437 472 413 229 671 706  69 737 140 908
 647 162 469 480 880 886 851 901 303 873 392 844  67 178 519 830 996 883
 410 573 681 313 938 414 939 379 401 266 825  77 154 270 465 283 244 818
 630  40 207 110 254 828 193 947 936 345 399 910 961  77 436 863 251 160
 101 646 902 705 414 278 760 196 337 837 427 720  10  56 584 586 725  66
 643 149 472  21  53 931 378 587 555 941]

Prime numbers in the array:
[463 229 647  67 883 313 379 401 283 193 947 863 251 101 337 643 149  53
 587 941]


##### 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [ ]:
import numpy as np

# Generating a NumPy array of daily temperatures for a month (30 days)
daily_temperatures = np.random.randint(20, 40, size=30)  # Random temperatures between 20°C and 40°C

print("Daily Temperatures:")
print(daily_temperatures)

# Calculating weekly averages
weekly_averages = [np.mean(daily_temperatures[i:i+7]) for i in range(0, len(daily_temperatures), 7)]

print("\nWeekly Averages:")
print(weekly_averages)